version: '3'

services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
          - "8000:80"
        volumes:
          - .:/symfony
          - ./docker/nginx:/etc/nginx/conf.d
          - ./var/logs:/var/log/nginx/
        depends_on:
          - php
          - mysql
        extra_hosts:
            - "host.docker.internal:host-gateway"
    php:
        build: 
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - .:/symfony
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        ports: 
            - "9000:9000"
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_autostart=off  remote_port=9003"
            PHP_IDE_CONFIG: "serverName=first"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        command: --innodb_use_native_aio=0
        ports:
            - "3306:3306"
        volumes:
            - ./var/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
        extra_hosts:
            - "host.docker.internal:host-gateway"
    adminer:
        image: adminer
        container_name: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
        extra_hosts:
            - "host.docker.internal:host-gateway"
